### ISSUE TITLE
Replace/remove usage of PAT

### ISSUE THREAD

**Issue by tenstad** [statnett/image-scanner-operator#552]
Ref https://github.com/statnett/image-scanner-operator/blob/6bf16f6a4428b89f05051aa0354d1243eef43c62/.github/workflows/release-please.yml#L22

Why is a PAT/App token needed?

## App Token

Why not use an App token instead?

### Required permissions

- Contents 
  Repository contents, commits, branches, downloads, releases, and merges.
- Pull requests 
  Pull requests and related comments, assignees, labels, milestones, and merges.

### Usage

```yaml
      - id: token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ steps.token.outputs.token }}
```
